# Generated by Django 5.2.4 on 2025-10-16 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nazwa tagu')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
            ],
            options={
                'verbose_name': 'Tag artykułu',
                'verbose_name_plural': 'Tagi artykułów',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NewsWebsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500, unique=True, verbose_name='URL strony')),
                ('domain', models.CharField(blank=True, max_length=200, verbose_name='Domena')),
                ('name', models.CharField(max_length=200, verbose_name='Nazwa serwisu')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywna')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
            ],
            options={
                'verbose_name': 'Serwis informacyjny',
                'verbose_name_plural': 'Serwisy informacyjne',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CrawlSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nazwa sesji')),
                ('status', models.CharField(choices=[('pending', 'Oczekuje'), ('running', 'W trakcie'), ('completed', 'Zakończona'), ('failed', 'Błąd'), ('cancelled', 'Anulowana')], default='pending', max_length=20, verbose_name='Status')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Rozpoczęto')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Zakończono')),
                ('total_articles', models.PositiveIntegerField(default=0, verbose_name='Całkowita liczba artykułów')),
                ('scraped_articles', models.PositiveIntegerField(default=0, verbose_name='Scrapowane artykuły')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawler.newswebsite', verbose_name='Serwis')),
            ],
            options={
                'verbose_name': 'Sesja crawlowania',
                'verbose_name_plural': 'Sesje crawlowania',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1000, unique=True, verbose_name='URL artykułu')),
                ('title', models.CharField(max_length=500, verbose_name='Tytuł artykułu')),
                ('original_content', models.TextField(verbose_name='Oryginalna treść artykułu (HTML)')),
                ('plain_text_content', models.TextField(verbose_name='Treść artykułu (plain text)')),
                ('published_date_normalized', models.DateTimeField(verbose_name='Data publikacji (dd.mm.yyyy HH:mm:ss)')),
                ('status', models.CharField(choices=[('success', 'Sukces'), ('failed', 'Błąd'), ('skipped', 'Pominięto')], default='success', max_length=20, verbose_name='Status')),
                ('http_status_code', models.PositiveIntegerField(blank=True, null=True, verbose_name='Kod odpowiedzi HTTP')),
                ('response_time', models.FloatField(blank=True, null=True, verbose_name='Czas odpowiedzi (s)')),
                ('content_length', models.PositiveIntegerField(blank=True, null=True, verbose_name='Długość zawartości')),
                ('error_message', models.TextField(blank=True, verbose_name='Komunikat błędu')),
                ('scraped_at', models.DateTimeField(auto_now_add=True, verbose_name='Scrapowano')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadane')),
                ('crawl_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crawler.crawlsession', verbose_name='Sesja')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawler.newswebsite', verbose_name='Serwis')),
            ],
            options={
                'verbose_name': 'Artykuł',
                'verbose_name_plural': 'Artykuły',
                'ordering': ['-published_date_normalized'],
            },
        ),
        migrations.CreateModel(
            name='ArticleTagRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawler.article', verbose_name='Artykuł')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawler.articletag', verbose_name='Tag')),
            ],
            options={
                'verbose_name': 'Relacja artykuł-tag',
                'verbose_name_plural': 'Relacje artykuł-tag',
                'unique_together': {('article', 'tag')},
            },
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['url'], name='crawler_art_url_0d7bd2_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['status'], name='crawler_art_status_4a65e0_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['published_date_normalized'], name='crawler_art_publish_c636a2_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['scraped_at'], name='crawler_art_scraped_004737_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['website'], name='crawler_art_website_8bb833_idx'),
        ),
    ]
